config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  root 'welcome#index'
  resources :posts do
    resources :steps, :only => [:create, :update, :edit, :destroy, :clear]
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  resources :users, :only => [:show, :index, :update, :edit, :destroy]
  resources :posts, :only => [:index, :show, :update, :edit, :destroy]
  resources :categories, :only => [:create, :update, :edit, :destroy]
  get 'tags/:tag', to: 'posts#index', as: :tag
  post 'update_step', to: 'steps#update_step', as: 'update_step'
  resources :steps do
    put :sort, on: :collection
  end
  resources :posts do
    get :autocomplete_category, :on => :collection
  end

  mount ActionCable.server => '/cable'
  match '*path' => redirect('/'), via: :get
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  ratyrate_rater
  has_many :comments
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable,
		 :omniauth_providers => [:facebook, :twitter, :vkontakte, :google_oauth2]
  has_many :posts
  def self.facebook_from_omniauth(auth)
	where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
	  user.provider = auth.provider
	  user.uid = auth.uid
	  user.email = auth.info.email
	  user.password = Devise.friendly_token[0,20]
	  user.image = auth.info.image
	  user.nickname = auth.info.name
	  user.save
	end
  end

  def self.vkontakte_from_omniauth(auth)
  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
	user.provider = auth.provider
	user.uid = auth.uid
	user.email = auth.info.first_name + '_' + auth.info.last_name + '@vk.com'
	user.password = Devise.friendly_token[0,20]
	user.image = auth.info.image
	user.nickname = auth.info.first_name + ' ' + auth.info.last_name
	user.save
  end
end

def self.twitter_from_omniauth(auth)
  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
	user.provider = auth.provider
	user.uid = auth.uid
	user.email = auth.info.name + '@twitter.com';
	user.password = Devise.friendly_token[0,20]
	user.image = auth.info.image
	user.nickname = auth.info.name
	user.save
  end
end

def self.google_from_omniauth(auth)
  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
	user.provider = auth.provider
	user.uid = auth.uid
	user.email = auth.info.email
	user.password = Devise.friendly_token[0,20]
	user.image = auth.info.image
	user.nickname = auth.info.name
	user.save
  end
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, only: [:edit, :update, :destroy]

	def index
		@users = User.all
	end

	def show
		@posts = @user.posts
	end

	def edit
		secureUser @user
	end

	def update
		secureUser @user
    respond_to do |format|
    	if @user.update(user_params)
        format.html { redirect_to @user }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
	end

	def destroy
		secureUser @user
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_path }
      format.json { head :no_content }
    end
  end

	private
		def secureUser user
			if user.id != current_user.id && current_user.isAdmin == false
				redirect_to root_path
			end
		end

		def set_user
	    @user = User.find(params[:id])
	  end

		def user_params
	    params.require(:user).permit(:nickname, :email, :about)
	  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <div class="row">
    <div class="input-group">
      <span class="input-group-addon"><%= t('users.form.nickname') %></span>
      <%= f.text_field :nickname, :class => "form-control" %>
    </div>
  </div><br>
  <div class="row">
    <div class="input-group">
      <span class="input-group-addon"><%= t('users.form.email') %></span>
      <%= f.text_field :email, :class => "form-control" %>
    </div>
  </div><br>
  <div class="row">
    <div class="input-group">
      <span class="input-group-addon"><%= t('users.form.about') %></span>
      <%= f.text_area :about, :class => "form-control" %>
    </div>
  </div><br>
  <div class="row user_form_button">
    <button type="submit" class="btn btn-secondary" style="width: 60%"><%= t('users.form.save') %></button>
  </div><br>
  <div class="row user_form_button">
    <%= link_to t('users.form.destroy'), @user, :class => "btn btn-danger", method: :delete, :style => "width: 60%", data: { confirm: 'Are you sure?' } %>
  </div>
  <div class="row user_form_button">
    <%= link_to t('users.form.back'), user_path(@user.id) %>
  </div>
<% end %>

app/views/users/edit.html.erb
<ul class="nav nav-tabs" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" href="#profile" role="tab" data-toggle="tab"><%= t('users.edit.profile') %></a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#buzz" role="tab" data-toggle="tab"><%= t('users.edit.posts') %></a>
  </li>
</ul>

<div class="tab-content">
  <div role="tabpanel" class="tab-pane fade active show" id="profile">
    <div class="container-fluid user_edit_tab">
  	  <div class="row header_edit">
  		  <%= t('users.edit.editing') %> <%= @user.nickname %>
  	  </div>
  	  <%= render 'form', user: @user %>
    </div>
  </div>
  <div role="tabpanel" class="tab-pane fade" id="buzz">
  	<div style="padding-left: 15%; padding-right:15%">
      <table class="table table-striped posts_index_table">
    	  <thead>
          <tr>
            <th style="text-align: center">#</th>
            <th style="text-align: center"><%= t('posts.table.name') %></th>
            <th style="text-align: center"><%= t('posts.table.update') %></th>
          </tr>
    	  </thead>
    	  <tbody>
    	    <% @user.posts.each_with_index do |post, index| %>
        	  <tr onclick="window.location.href='<%= post_path(post.id) %>'">
              <th scope="row comments_image"><%= index + 1 %></th>
      	      <td><%= post.name %></td>
      		    <td><%= post.updated_at.strftime("%d.%m.%y, %H:%M") %></td>
            </tr>
  	      <% end %>
    	  </tbody>
  	  </table>
  	</div>
  </div>
</div>

app/views/users/index.html.erb
<div class="user_edit_padding">
  <table class="table table-striped user_edit_table">
    <thead>
      <tr>
        <th>#</th>
        <th><%= t('users.index.header.avatar') %></th>
        <th><%= t('users.index.header.username') %></th>
        <th><%= t('users.index.header.posts') %></th>
        <th><%= t('users.index.header.email') %></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each_with_index do |user, index| %>
        <tr onclick="window.location.href='<%= user_path(user.id) %>'">
      	<th scope="row" class="user_table_inner"><%= index + 1 %></th>
      	<td><img src=<%= user.image %> width="50" height="50" style="border-radius: 50%"></td>
      	<td class="user_table_inner"><%= user.nickname %></td>
      	<td class="user_table_inner"><%= user.count_Posts %></td>
      	<td class="user_table_inner"><%= user.email %></td>
        </tr>
  	  <% end %>
    </tbody>
  </table>
</div>

app/views/users/show.html.erb
<div class="container-fluid user_show_body">
	<div class="row header_show">
		<div class="col-lg-6">
			<%= t('users.show.profile') %>   <%= @user.nickname %>
		</div>
		<div class="col-lg-6 show_header_link">
			<% if current_user && (@user.id == current_user.id || current_user.isAdmin) %>
				<%= link_to t('users.show.edit'), edit_user_path(@user.id), :class => "btn btn-secondary" %>
			<% end %>
		</div>
	</div>
	<div class="row body_show">
		<div class="col-lg-2">
			<img src=<%= @user.image %> class="img-fluid img_Show" width="150">
		</div>
		<div class="col-lg-10 content_show">
			<div>
			  <a class="btn btn-social-icon btn-lg ">
			    <i class="fa fa-envelope"></i>
			  </a>
			  <%= @user.email %><br>
			</div>
			<div><%= t('users.show.about') %><%= @user.about %><br></div>
		</div>
	</div>

	<div>
		<table class="table table-striped" style="text-align: center">
  		<thead>
	      <tr>
	        <th class="comments_image">#</th>
	        <th class="comments_image"><%= t('posts.table.name') %></th>
	        <th class="comments_image"><%= t('posts.table.update') %></th>
	      </tr>
  	  </thead>
  	  <tbody>
  	    <% @user.posts.each_with_index do |post, index| %>
      	  <tr onclick="window.location.href='<%= post_path(post.id) %>'">
            <th scope="row" class="comments_image"><%= index + 1 %></th>
    	    	<td><%= post.name %></td>
    				<td><%= post.updated_at.strftime("%d.%m.%y, %H:%M") %></td>
          </tr>
	    	<% end %>
  	  </tbody>
	  </table>
	</div>
</div>