config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  root 'welcome#index'
  resources :posts do
    resources :steps, :only => [:create, :update, :edit, :destroy, :clear]
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  resources :users, :only => [:show, :index, :update, :edit, :destroy]
  resources :posts, :only => [:index, :show, :update, :edit, :destroy]
  resources :categories, :only => [:create, :update, :edit, :destroy]
  get 'tags/:tag', to: 'posts#index', as: :tag
  post 'update_step', to: 'steps#update_step', as: 'update_step'
  resources :steps do
    put :sort, on: :collection
  end
  resources :posts do
    get :autocomplete_category, :on => :collection
  end

  mount ActionCable.server => '/cable'
  match '*path' => redirect('/'), via: :get
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/step.rb
class Step < ApplicationRecord
	belongs_to :post
	acts_as_list
	default_scope { order('position ASC') }
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  before_action :set_step, only: [:edit, :destroy]
  before_action :authenticate_user!, only: [:edit, :create, :update_step, :destroy]
  skip_before_action :verify_authenticity_token
  respond_to :js, :json, :html
  # GET /steps/1/edit
  def edit
    secureEnter @step
  end

  # POST /steps
  # POST /steps.json
  def create
    @post = Post.find(params[:post_id])
    @step = Step.new(:post=>@post)
    secureEnter @step
    @step = Step.create(step_params)
    @step.content = ""
    respond_to do |format|
      if @step.save
        format.html { redirect_to edit_post_path(@post.id), notice: 'Step was successfully created.' }
        format.json { render :show, status: :created, location: @step }
      else
        format.html { render :new }
        format.json { render json: @step.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /steps/1
  # DELETE /steps/1.json
  def destroy
    secureEnter @step
    @step.destroy
    respond_to do |format|
      format.html { redirect_to edit_post_path(@step.post.id) }
      format.json { head :no_content }
    end
  end

  def update_step
    @step = Step.find(params[:id])
    secureEnter @step
    @step.content = params[:data_value]
    @step.save
  end

  def sort
    params[:order].each do |key,value|
      Step.find(value[:id]).update_attribute(:position,value[:position])
    end
  end

  private

    def set_step
      @step = Step.find(params[:id])
    end

    def secureEnter step
      if step.post.user_id != current_user.id && current_user.isAdmin == false
        redirect_to root_path
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def step_params
      params.require(:step).permit(:post_id, :name)
    end
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/views/steps/edit.html.erb
<div class="container-fluid">
  <div class="row step_edit_header">
    <div class="col-lg-2 steps_edit_add_new"><%= t('steps.edit.addNew') %></div>
    <div class="col-lg-4">
      <a class="btn btn-social-icon btn-success btn-md" onclick="create_new_text()">
        <i class="fa fa-file-text steps_edit_icons"></i>
      </a>
      <a class="btn btn-social-icon btn-success btn-md" id="upload_widget_opener">
        <i class="fa fa-picture-o steps_edit_icons"></i>
      </a>
      <a class="btn btn-social-icon btn-success btn-md" onclick="create_new_video()">
        <i class="fa fa-video-camera steps_edit_icons"></i>
      </a>
    </div>
    <div class="col-lg-3"></div>
    <div class="col-lg-3">
      <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
        <div class="btn-group mr-2" role="group" aria-label="First group">
          <%= link_to t('steps.edit.destroyButton'), post_step_path(@step.id), method: :delete, :class => "btn btn-danger"%>
          <button type="button" class="btn btn-success edit_step_success" onclick="ajax_request()" id="<%= @step.id %>Button"><%= t('steps.edit.saveButton') %></button>
        </div>
      </div>
    </div>
  </div>
</div>
<ol id="main_block" class="drag_list">
  <% if @step.content != '' %>
    <% @step.content.split("%block%").each_with_index do |item, index| %>
      <% if item.include? "%text%" %>
        <li class='ui-sortable-handle' id="<%= index+1000 %>">
          <div class='row block text'>
            <div class="block_text_field">Text</div>
            <textarea class="form-control block_text_area" rows="3"><%= item.split("%text% >")[1].split("</p>")[0].html_safe %></textarea>
            <button id="<%= index+1000 %>_button" class="btn btn-danger" onclick="delete_function(id)">Destroy</button>
          </div>
        </li>
      <% end %>
      <% if item.include? "%image%" %>
        <li class='ui-sortable-handle' id="<%= index+1000 %>">
          <div class='row block image'>
            <div class="block_text_field">Image</div>
            <div class='block_image'>
              <img src=<%= item.split("src=")[1].split(' class')[0].html_safe %>>
            </div>
            <button id="<%= index+1000 %>_button" class="btn btn-danger" onclick="delete_function(id)">Destroy</button>
          </div>
        </li>
      <% end %>
      <% if item.include? "%video%" %>
        <li class='ui-sortable-handle' id="<%= index+1000 %>">
          <div class='row block video'>
            <div class="block_text_field">Video</div>
            <input type="text" placeholder="Your link" class="form-control block_text_area" value="https://www.youtube.com/watch?v=<%= item.split('embed/')[1].split("' frameborder")[0] %>">
            <button id="<%= index+1000 %>_button" class="btn btn-danger" onclick="delete_function(id)">Destroy</button>
          </div>
        </li>
      <% end %>
    <% end %>
  <% end %>
</ol>
<script src="//widget.cloudinary.com/global/all.js" type="text/javascript"></script>