config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  root 'welcome#index'
  resources :posts do
    resources :steps, :only => [:create, :update, :edit, :destroy, :clear]
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  resources :users, :only => [:show, :index, :update, :edit, :destroy]
  resources :posts, :only => [:index, :show, :update, :edit, :destroy]
  resources :categories, :only => [:create, :update, :edit, :destroy]
  get 'tags/:tag', to: 'posts#index', as: :tag
  post 'update_step', to: 'steps#update_step', as: 'update_step'
  resources :steps do
    put :sort, on: :collection
  end
  resources :posts do
    get :autocomplete_category, :on => :collection
  end

  mount ActionCable.server => '/cable'
  match '*path' => redirect('/'), via: :get
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
	include SearchCop
	belongs_to :user
	belongs_to :category
	has_many :steps
	has_many :comments
	acts_as_taggable
	ratyrate_rateable 'original_score'

	search_scope :search do
    attributes :name, :preview
		attributes comment: 'comments.content'
		attributes step: ['steps.content', 'steps.name']
  end

	def avg_rating_dimension(post)
    array = Rate.where(rateable_id: id, rateable_type: 'Post').where(dimension: 'original_score')
    stars = array.map {|post| post.stars }
    star_count = stars.count
    stars_total = stars.inject(0){|sum,x| sum + x }
    score = stars_total / (star_count.nonzero? || 1)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  autocomplete :category, :category_id

  # GET /posts
  # GET /posts.json
  def index
    if params[:tag]
      @posts = Post.tagged_with(params[:tag]).includes(:category)
    else
      if params[:val]
        @posts = Post.search(params[:val]).includes(:category)
      else
        @posts = Post.all.includes(:category)
      end
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.includes(:tags).find(params[:id])
    @comments = @post.comments.includes(:user)
    @steps = @post.steps.paginate(:per_page => 1, :page => params[:page])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @steps }
      format.js
end
  end

  # GET /posts/new
  def new
    @post = Post.new
    @categories = Category.all
  end

  # GET /posts/1/edit
  def edit
    if @post.user_id != current_user.id && current_user.isAdmin == false
      redirect_to root_path
    end
    @step = Step.new
    @steps = @post.steps.order("position")
  end

  # POST /posts
  # POST /posts.json
  def create
    if post_params[:name].empty? || post_params[:category_id].empty?
      redirect_to new_post_path
    else
      id_Categ = Category.where(:name => post_params[:category_id])[0]
      if id_Categ == nil
        redirect_to new_post_path
      else
        @post = createConfig @post, id_Categ
        if @post.preview == ""
          @post.preview = "http://mirgif.com/KARTINKI/kosmos/kosmos-42.jpg"
          @post.save
        end
        respond_to do |format|
          format.html { redirect_to @post}
          format.json { render :show, status: :created, location: @post }
        end
    end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to edit_post_path(@post.id), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    current_user.count_Posts -= 1
    current_user.save
    respond_to do |format|
      format.html { redirect_to posts_path, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    @posts = Post.search(params[:val]).includes(:category)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    def createConfig post, id_Categ
      post = current_user.posts.create(post_params)
      post.category_id = id_Categ.id
      post.save
      current_user.count_Posts += 1
      current_user.save
      post
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:user_id, :name, :rate, :tag_list, :preview, :category_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
  def convertCategory list
    final_string = ""
    list.length.times do |i|
      final_string += list[i].name + "_"
    end
    final_string.split("_").join(",")
  end
end

app/views/posts/_post.html.erb
<div class="row post_partial_main">
  <% @posts.each do |post| %>
    <div class="col-lg-4">
        <div class="card post_partial_card" onclick="window.location.href='<%= post_path(post.id) %>'">
          <img class="card-img-top post_partial_image" src=<%= post.preview %> alt="Card image cap">
          <div class="card-block">
            <h4 class="card-title">
              <% if post.name.length >=20 %>
                <%= post.name[0..15] %>...
              <% else %>
                <%= post.name %>
              <% end %>
            </h4>
            <p class="card-text">
              <div class="badge badge-pill badge-warning tags"><%= post.category.name %></div>
            </p>
          </div>
        </div>
    </div>
  <% end %>
</div>

app/views/posts/_steps_List_Show.html.erb
<% @steps.each do |step| %>
  <strong class="posts_show_step_header"><%= step.name %></strong>
  <% step.content.split("%block%").each do |item| %>
    <div class='row show_block'>
      <div class='col-lg-12'>
        <%= item.html_safe %>
      </div>
    </div>
  <% end %>
<% end %>

<div class="row posts_show_row_paginate">
  <div class="col-lg-4"></div>
  <div class="col-lg-4">
    <%= will_paginate @steps, :page_links => false %>
  </div>
  <div class="col-lg-4"></div>
</div>

app/views/posts/edit.html.erb
<div class="container-fluid">
  <div class="row post_edit_block">
    <div class="col-lg-4 edit_post_column">
      <div class="comments_image"><%= t('posts.edit.header') %></div>
      <%= form_for(@post) do |f| %>
        <div class="input-group">
          <span class="input-group-addon"><%= t('posts.edit.name') %></span>
          <%= f.text_field :name, :class => "form-control" %>
        </div>
        <button type="submit" class="btn btn-facebook edit_post_button"><%= t('posts.edit.update') %></button>
        <%= button_to t('posts.edit.buttons.destroy'), post_path(@post.id), method: :delete , :style =>"margin-bottom: 20%", :class => "btn btn-danger edit_post_button", data: { confirm: "Are you sure?"} %>
      <% end %>
      <div class="comments_image"><%= t('posts.edit.form.create') %></div>
      <%= form_for [@post, @step] do |f| %>
        <div class="field" style = "display:none">
          <%= f.label :post_id %>
          <%= f.number_field :post_id, :value => @post.id %>
        </div>
        <div class="input-group">
          <span class="input-group-addon"><%= t('posts.edit.form.step') %></span>
          <%= f.text_field :name, :class => "form-control" %>
        </div>
        <button type="submit" class="btn btn-success posts_edit_form_button"><%= t('posts.edit.form.button') %></button>
      <% end %>
      <div class="posts_edit_button_group">
        <%= link_to t('posts.edit.form.links.switch'), post_path(@post.id) %>
        <button onclick="updateDiv()" class="btn btn-secondary"><%= t('posts.edit.buttons.refresh') %></button>
      </div>
    </div>
    <div class="col-lg-8" id="reloading">
      <div>
        <table class="table table-striped posts_index_table" style="margin-top:0">
          <thead>
            <tr>
              <th class="comments_image">#</th>
              <th class="comments_image"><%= t('posts.edit.table.step') %></th>
              <th class="comments_image"><%= t('posts.edit.table.update') %></th>
            </tr>
          </thead>
          <tbody id="steps_list">
            <% @steps.each_with_index do |step, index| %>
              <tr class="list_item" data-id = "<%= step.id %>" onclick="window.location.href='<%= edit_post_step_path(id: step.id, post_id: step.post.id) %>'">
                <th scope="row" class="comments_image"><%= index + 1 %></th>
                <td><%= step.name %></td>
                <td><%= step.updated_at.strftime("%d.%m.%y, %H:%M") %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="posts_index_main">
  <div class="container-fluid">
    <%= render 'post' %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container-fluid posts_new_body">
  <div class="row post_new_header"><%= t('posts.new.name') %></div>
  <%= form_for(@post) do |f| %><br>
    <div class="row">
      <div class="input-group">
        <span class="input-group-addon"><%= t('posts.form.name') %></span>
        <%= f.text_field :name, :class => "form-control" %>
      </div>
    </div><br>
    <div class="row">
      <div class="input-group">
        <span class="input-group-addon"><%= t('posts.form.preview') %></span>
        <%= f.text_field :preview, :class => "form-control" %>
      </div>
    </div><br>
    <div class="row">
      <div class="input-group">
        <span class="input-group-addon"><%= t('posts.form.tags') %></span>
        <%= f.text_field :tag_list, :class => "form-control" %>
      </div>
    </div><br>
    <div class="row">
      <div class="input-group">
        <span class="input-group-addon"><%= t('posts.form.category') %></span>
        <input class="awesomplete form-control" type="text" name="post[category_id]" id="post_category_id", data-list=<%= convertCategory(@categories) %>>
      </div>
    </div><br>
    <div class="row posts_new_button">
      <button type="submit" class="btn btn-secondary" style="width: 60%"><%= t('posts.form.button') %></button>
    </div><br>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="container-fluid body_posts_show">
  <div class="row header_posts_show">
    <div class="col-lg-6">
      <%= @post.name %>
    </div>
    <div class="col-lg-3 posts_show_header_buttons">
      <% if current_user %>
        <%= rating_for @post, "original_score" %>
      <% end %>
    </div>
    <div class="col-lg-3 posts_show_header_buttons">
      <% if (current_user && (@post.user_id == current_user.id || current_user.isAdmin)) %>
        <%= link_to t('posts.show.links.edit'), edit_post_path(@post.id), class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
  <div class="posts_show_tags">
    <% @post.tags.each do |tag| %>
      <%= link_to tag, tag_path(tag.name), :class => "badge badge-pill badge-danger tags" %>
    <% end %>
  </div>
  <div id="steps_list_show">
    <%= render 'steps_List_Show' %>
  </div>
  <% if user_signed_in? %>
    <div id="comments" style="margin-top:1%">
      <%= render @comments %>
    </div>
    <div class="row" style="margin-top:2%">
      <div class="input-group">
        <span class="input-group-addon"><%= t('posts.show.comment') %></span>
        <input id="input_text" data-post-id=<%= @post.id %> data-user-id=<%= current_user.id %> type="text" data-behavior="post_speaker" class="form-control">
      </div>
    </div><br>
  <% else %>
    <div class="row" style="margin-top:2%;margin-bottom:2%">
      <div class="col-lg-3"></div>
      <div class="col-lg-6"><strong><%= t('posts.show.unable') %></strong></div>
      <div class="col-lg-3"></div>
    </div>
  <% end %>
</div>

app/views/posts/show.js.erb
$("#steps_list_show").html("<%= escape_javascript(render("steps_list_show")) %>");