config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  root 'welcome#index'
  resources :posts do
    resources :steps, :only => [:create, :update, :edit, :destroy, :clear]
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  resources :users, :only => [:show, :index, :update, :edit, :destroy]
  resources :posts, :only => [:index, :show, :update, :edit, :destroy]
  resources :categories, :only => [:create, :update, :edit, :destroy]
  get 'tags/:tag', to: 'posts#index', as: :tag
  post 'update_step', to: 'steps#update_step', as: 'update_step'
  resources :steps do
    put :sort, on: :collection
  end
  resources :posts do
    get :autocomplete_category, :on => :collection
  end

  mount ActionCable.server => '/cable'
  match '*path' => redirect('/'), via: :get
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Life_Hacker</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag  'application', media: 'all'%>
    <link rel="stylesheet" href="http://www.atlasestateagents.co.uk/css/tether.min.css">
    <script src="https://npmcdn.com/tether@1.2.4/dist/js/tether.min.js"></script>
    <%= javascript_include_tag 'application'%>
    <%= stylesheet_link_tag 'posts'%>
    <%= javascript_include_tag 'awesomplete'%>
    <%= stylesheet_link_tag 'awesomplete', :async => true %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <script src="https://npmcdn.com/bootstrap@4.0.0-alpha.5/dist/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  </head>

  <body>
    <div class="container-fluid header">
      <div class="row">
        <div class="col-lg-3 align_class" onclick='window.location.href = "/"'><h3>Life_hacker</h3></div>
        <div class="col-lg-3">
          <div class="input-group">
            <input type="text" class="form-control" id="main_search_field" placeholder=<%= t('header.form.placeholder') %> aria-describedby="basic-addon1">
            <span class="input-group-btn">
              <button class="btn btn-secondary" type="button" onclick="searchPosts()">Go!</button>
            </span>
          </div>
        </div>
        <div class="col-lg-1 a">
          <%= link_to t('header.links.users'), users_path, :class => "link_header"%>
        </div>
        <div class="col-lg-3 a">
          <%= link_to t('header.links.posts'), posts_path, :class => "link_header"%>
        </div>
        <% if user_signed_in? %>
          <div class="col-lg-2 login">
            <div class="dropdown">
              <img src=<%= current_user.image%> class="avatar_login dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <div class="dropdown-menu dropdown-menu-left menu" aria-labelledby="dropdownMenuButton">
                <div class = "dropdown-item menu_nickname"><%= current_user.nickname %></div>
                <% if current_user.isAdmin %>
                  <div class = "dropdown-item" data-toggle="modal" data-target=".category_Create">Create category</div>
                <% end %>
                <%= link_to t('header.profile.create'), new_post_path, :class => "dropdown-item menu" %>
                <%= link_to t('header.profile.edit'), edit_user_path(current_user.id), :class => "dropdown-item menu" %>
                <%= link_to t('header.profile.logout'), destroy_user_session_path, method: :delete, :class => "dropdown-item menu" %>
              </div>
            </div>
          </div>
        <% else %>
          <div class="col-lg-2 login">
            <div data-toggle="modal" data-target=".bd-example-modal-sm"><%=t ('header.links.login') %></div>
          </div>
        <% end %>
      </div>
    </div>

    <div class="modal fade bd-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-sm">

      <div class="modal-content login_modal_body">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel"><%= t('header.modal.login') %></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <a class="btn btn-social-icon btn-lg btn-facebook" href="/users/auth/facebook">
            <i class="fa fa-facebook"></i>
          </a>
          <a class="btn btn-social-icon btn-lg btn-vk" href="/users/auth/vkontakte">
            <i class="fa fa-vk"></i>
          </a>
          <a class="btn btn-social-icon btn-lg btn-twitter" href="/users/auth/twitter">
            <i class="fa fa-twitter"></i>
          </a>
          <a class="btn btn-social-icon btn-lg btn-google" href="/users/auth/google_oauth2">
            <i class="fa fa-google"></i>
          </a>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal"><%= t('header.modal.button') %></button>
        </div>
      </div>
    </div>
  </div>

  <div class="modal fade bd-example-modal-md category_Create" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm">
      <div class="modal-content modal_category">
        <div class="modal-body">
          <%= form_for(@category) do |f| %><br>
            <div class="row">
              <div class="input-group">
                <span class="input-group-addon"><%= t('posts.form.name') %></span>
                <%= f.text_field :name, :class => "form-control" %>
              </div>
            </div><br>

            <div class="row modal_category_row">
              <button type="submit" class="btn btn-secondary modal_category_button">Create category</button>
            </div><br>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <%= yield %>
  <footer class="footer">
    <div class="container">
      <div class="row">
        <div class="col-lg-2">
          <div class="dropup">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= t('footer.buttons.language') %>
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
              <div class ="dropdown-item btn btn-secondary"><%= link_to_unless I18n.locale == :en, t('footer.buttons.english'), locale: :en %></div>
              <div class ="dropdown-item btn btn-secondary"><%= link_to_unless I18n.locale == :ru, t('footer.buttons.russian'), locale: :ru %></div>
            </div>
          </div>
        </div>
        <div class="col-lg-10"></div>
      </div>
    </div>
  </footer>
</body>
</html